server:
  port: 8080
spring:
  application:
    name: spring-gateway-server
ribbon:
  ReadTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 130000

eureka:
  instance:
    hostname: localhost
    port: 8761
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    instance:
      preferIpAddress: true


zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  ribbon:
    eager-load:
      enabled: true
  routes:
    springoauthserver:
      sensitiveHeaders:
      path: /oauth/**
      stripPrefix: false
      serviceId: spring-oauth-server
    productwebservice:
      sensitiveHeaders:
      path: /products/**
      stripPrefix: false
      service-id: product-web-services
    orderwebservice:
      sensitiveHeaders:
      path: /orders/**
      stripPrefix: false
      service-id: order-web-services

management:
  endpoints:
    web:
      exposure:
        include: "*"